USE [master]
GO

/****** Object:  Database [MarketShop]    Script Date: 11/26/2020 12:54:22 PM ******/
CREATE DATABASE [MarketShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MarketShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MarketShop.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MarketShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MarketShop_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MarketShop] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MarketShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MarketShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MarketShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MarketShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MarketShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MarketShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [MarketShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MarketShop] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MarketShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MarketShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MarketShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MarketShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MarketShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MarketShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MarketShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MarketShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MarketShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MarketShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MarketShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MarketShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MarketShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MarketShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MarketShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MarketShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MarketShop] SET RECOVERY FULL 
GO

ALTER DATABASE [MarketShop] SET  MULTI_USER 
GO

ALTER DATABASE [MarketShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MarketShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MarketShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MarketShop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MarketShop] SET  READ_WRITE 
GO


